switched to swiperJS, removed flowbite from package.json and tailwind…
aryanteng/iiitd-cse pull request #22
Opened 2024-03-11 19:46 UTC by ritsiiitd

… switched to swiperJS, removed flowbite from package.json and tailwind…

2024-03-13 06:20 UTC, aryanteng requested changes
<img width="1256" alt="Screenshot 2024-03-13 at 11 42 36 AM" src="https://github.com/aryanteng/iiitd-cse/assets/77500690/2f0f8e8c-f74d-4944-a543-6110c7a56892">
The swiper looks good. Here are some changes:
1. Swiper Js arrows do not have our primary color, this can be done using custom CSS styles in the globals.css I think.
2. Swiper should be made infinite, meaning that after click next to the last photo I should come to the first.
3. The arrows should be outside of the image, not overlapping.

2024-03-16 10:21 UTC, ritsiiitd commented
> <img alt="Screenshot 2024-03-13 at 11 42 36 AM" width="1256" src="https://private-user-images.githubusercontent.com/77500690/312332442-2f0f8e8c-f74d-4944-a543-6110c7a56892.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1ODQ1NDYsIm5iZiI6MTcxMDU4NDI0NiwicGF0aCI6Ii83NzUwMDY5MC8zMTIzMzI0NDItMmYwZjhlOGMtZjc0ZC00OTQ0LWE1NDMtNjExMGM3YTU2ODkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDEwMTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYmEyOGE4MGIwNWExYjM1ZjUxNmRiMmQ5ZjBmNGQ2Njg4NjQ5Yjc3NmY2ZTkxOGQyNjBkZTAyOTEwZTFmYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XVuUpPA8il2S-8iMhgn-DG4LJQcRBDWUxhlCTEsoaPE"> The swiper looks good. Here are some changes: 1. Swiper Js arrows do not have our primary color, this can be done using custom CSS styles in the globals.css I think. 2. Swiper should be made infinite, meaning that after click next to the last photo I should come to the first. 3. The arrows should be clearly distinct from the image, either make them thicker and white, or give our primary, whichever makes the contrast best.

Fixed

2024-03-16 14:13 UTC, aryanteng requested changes

2024-03-16 14:13 UTC, aryanteng commented on components/admissions/phd/CustomCarousel.js
> +          <div className=" h-80 flex justify-center items-center">
please use a map function for this, do not repeat components

2024-03-16 14:13 UTC, aryanteng commented on components/admissions/phd/CustomCarousel.js
> +export default function App() {
why App?

2024-03-16 14:15 UTC, aryanteng commented
<img width="1386" alt="Screenshot 2024-03-16 at 7 43 58 PM" src="https://github.com/aryanteng/iiitd-cse/assets/77500690/a5110dad-10a2-4961-92d5-45ae97e93808">
it's not round, it's oval, i think you need to fix the width and height equal and rounded-full for this to work.

2024-03-21 08:50 UTC, ritsiiitd commented
> <img alt="Screenshot 2024-03-16 at 7 43 58 PM" width="1386" src="https://private-user-images.githubusercontent.com/77500690/313409811-a5110dad-10a2-4961-92d5-45ae97e93808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTEzMzAsIm5iZiI6MTcxMTAxMTAzMCwicGF0aCI6Ii83NzUwMDY5MC8zMTM0MDk4MTEtYTUxMTBkYWQtMTBhMi00OTYxLTkyZDUtNDVhZTk3ZTkzODA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA4NTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMmE3YzUzN2FiNjRhNTI0YTk4MTEwODQ4NmQ3MzdiYjk5MDY1Y2RiY2FiMmJkOWRkOTZkNGM3ZDBmMmEzNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kODI7Tp2dQ3bKK_KCRL0Ug3sjhnDAujfRUmAR69wkDM"> it's not round, it's oval, i think you need to fix the width and height equal and rounded-full for this to work.

Updated✔

2024-03-23 18:02 UTC, aryanteng approved these changes

2024-03-23 18:16 UTC, merged